require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.colorscheme"
-- require "user.plugins.nvim-tree"
require "user.plugins.gitsigns"
-- require "user.plugins.gruvbox"
require "user.plugins.lualine"
require "user.plugins.telescope"
require "user.plugins.bufferline"
require "user.plugins.cmp"
require "user.plugins.codeium"
require "user.plugins.lsp-config"
require "user.plugins.oil"
require "user.plugins.surround"
--require "user.plugins.codesnap"
